name: "Hello World!"
description: "Greet the world"
author: "GIS"

inputs:
        MY_NAME:
                description: "Who to greet"
                required: true
                default: "World"

runs:
        using: "docker"

