name: GitHub Actions Build
on: 
  push:
    branches: 
      [ task5 ]
jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
             mkdir task5/3rdparty
             cd task5/3rdparty
             git clone https://github.com/google/googletest.git
             cp -f -r ./googletest/. .
             cd ../

             mkdir build
             cd build
             cmake ../
             make
             sudo make install
             echo "!!!1"
             pwd
             echo "!!!2"
             ls bin
             echo "!!!3"
             ls lib
             echo "!!!4"
             ls /usr/local/exe/bin
             echo "!!!5"
             ls ../bin
             echo "!!!6"
             ls ../lib
             echo "!!!7"


      - name: Test
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          exec-path: task5/bin/CTestExe #/home/runner/work/MIPT_ATP/MIPT_ATP/task5/bin/CTestExe #tas5/bin
          report-path: report.xml
          working-directory: . 


      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: Distributive
          path: |
            task5/bin
            task5/lib
                  #task5/bin
                  #task5/lib
                  #/home/runner/work/MIPT_ATP/MIPT_ATP/task5/bin/ #task5/bin #build/bin
                  #/home/runner/work/MIPT_ATP/MIPT_ATP/task5/lib/ #task5/lib #build/lib

       
